### PR TITLE
Add a configurable prefix for sqlite tables

### PR DESCRIPTION
**Pull request by peterschwarz**
Add a configurable prefix for all of the tables created/used by the SqliteDatabase implementation.  This allows for multiple transact Database instances to be applied to a single sqlite database file.

### CODE REVIEW

**Comment by jsmitchell** [comment]
You should consider moving all these queries to prepared statements in a different PR.

**Comment by jsmitchell** [comment]
> You should consider moving all these queries to prepared statements in a different PR.

Or maybe prepare_cached() is already doing that?

**Comment by peterschwarz** [comment]
`prepare_cached` should be doing that. If the format calls are expensive (amortized) we could consider pre-computing the sql strings.

**Comment by peterschwarz** [comment]
Changed the default prefix to `"transact_"` and removed the double prefix.

**Pull request merged**
